# Generated by Django 5.2.8 on 2025-12-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_despesa_classificacao_alter_despesa_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categoria'),
        ),
        migrations.AddField(
            model_name='receita',
            name='classificacao',
            field=models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], default='variavel', max_length=10),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(),
        ),
    ]
