# Generated by Django 6.0 on 2025-12-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_receita_classificacao_alter_receita_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(default='geral', max_length=20),
        ),
    ]
