# Generated by Django 5.2.8 on 2025-12-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], default='variavel', max_length=10, null=True),
        ),
    ]
